name = "riot-festival-schedule"
compatibility_date = "2025-01-01"
assets = { directory = ".", not_found_handling = "single-page-application" }

[env.production]
name = "riot-festival-schedule"

[env.staging]
name = "riot-festival-schedule-staging"
